class TestUser:

    def test_create_user(self):
        ...

    def test_get_user_by_name(self):
        ...

    def test_update_user(self):
        ...

    def test_delete_user(self):
        ...